### ISSUE TITLE
Uniswap Demo: Meta Issue

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/fe#148]
## Uniswap Demo

To drive the development of Fe we are going to write the Uniswap Contracts in Fe with the intention to create a working demo. It is expected that this will drive language features and reveal bugs during the process.

This issue is intended to be a **meta issue** meaning it should collect high level todos which are supposed to be linked to dedicated Github issues that describe the single work item in more detail.

### TODOS:

- [ ] Decide on which Uniswap version to target (v1 or v2)
- [ ] Write the contracts in Fe and get them to type check
- [ ] Need a solution to create instances of external contracts (comparable to [this](https://github.com/Uniswap/uniswap-v2-core/blob/4dd59067c76dea4a0e8e4bfdda41877a6b16dedc/contracts/UniswapV2Factory.sol#L30-L32))

*Please edit this issue and add items*

**Comment by g-r-a-n-t** [comment]
I've started working on a document for this https://notes.ethereum.org/@O5cy5Wl3T4ueffZS8i9mQg/S1ZsQ_z0D. Features are listed by importance and brief descriptions with examples are given.

**Comment by cburgdorf** [comment]
This has been resolved
