### ISSUE TITLE
Decompose Fe -> Yul compiler pass

### ISSUE THREAD

**Issue by g-r-a-n-t** [ethereum/fe#31]
Currently, we have a single compiler pass that maps Fe ASTs generated by the parser to Yul. This pass is responsible for both context-sensitive analysis and mapping Fe to Yul. As the project grows in complexity, it will become difficult to manage both of these responsibilities in one pass and would result in a codebase that's difficult to audit.

We can improve the situation by introducing a pass before the Fe to Yul mapper that is responsible for both deeper validation of the source program and for providing the mapper pass with enough information to correctly map expressions.

Let's illustrate with the guest book contract:

```
/* guest_book.vy */
type BookMsg = bytes[100]

contract GuestBook:
    pub guest_book: map<address, BookMsg>

    event Signed:
        idx book_msg: BookMsg

    pub def sign(book_msg: BookMsg):
        self.guest_book[msg.sender] = book_msg

        emit Signed(book_msg=book_msg)

    pub def get_msg(addr: address) -> BookMsg:
        return self.guest_book[addr]
```

**Compilation of the returned expression in `get_msg` goes roughly like this:**

*context/mapper pass*
- gets the type of `self.guest_book` from the contract scope and maps it to a Yul expression (its storage index) then returns this information to the caller.
- gets the type information for `addr` from the function scope and maps it to a Yul expression then returns this information to the caller
- determines the type of `self.guest_book[addr]` given the type of `self.guest_book` and maps it to a Yul expression then returns this information to the caller

**It should instead go like this:**

*context pass*
- gets the type of `self.guest_book` from the contract sope and stores it
- gets the type of `addr` from the function scope and stores it
- determines the type of `self.guest_book[addr]` and stores it

*mapper pass*
- maps `self.guest_book` to a Yul expression given the expression type from the previous pass
- maps `addr` to a Yul expression given the expression type from the previous pass
- maps `self.guest_book[addr]` to a Yul expression given the expression type from the previous pass

The second method separates concerns nicely and conforms more closely with standard compiler design.

**todo:**
Determine what the data structure built up by the context pass should be.

**Comment by g-r-a-n-t** [comment]
I've written some [code](https://github.com/ethereum/fe/commit/305515699165ff1f29e0d979103eb24d56b1c481) to express how I think this should be done.

In the existing single pass compiler, we gather information about context using shared [`Scope`](https://github.com/ethereum/fe/blob/4bd735adac4df4f7cf805a07de7a2348aee6ec0a/compiler/src/yul/namespace/scopes.rs#L59) instances that are linked together. When certain elements of the Fe AST are being mapped to Yul, we access the given scope to lookup whatever information is needed. Similarly, when we map Fe expressions to Yul, we return extra data (in the form of an  [`ExtExpression`](https://github.com/ethereum/fe/blob/4bd735adac4df4f7cf805a07de7a2348aee6ec0a/compiler/src/yul/mappers/expressions.rs#L35)) and use that to better understand how Yul expressions should be formed.

I suggest that we remove all of the context-understanding work being done in the compiler pass and replace it with a single immutable `context` instance that is made accessible to each mapper function. It would contain general information about the module and would map contextual information to AST elements using their [`span`](https://github.com/ethereum/fe/blob/4bd735adac4df4f7cf805a07de7a2348aee6ec0a/parser/src/span.rs#L8) as a unique key. This `context` instance would be built by a semantic analysis pass that takes place just before Fe -> Yul compilation.

```rust
pub struct Context {
    expressions: HashMap<Span, Expression>,
    ...
}
```
*Partial definition of `Context`.*

Spans are structs generated by the parser that tell you where in the source program a given AST element is located. Below, I've annotated the same expression discussed in the initial comment with spans and show how they would be used to lookup relevant information in the context instance.

```
              span 3
                |--|
self.guest_book[addr]
|-------------|
     span 2
|-------------------|
       span 1
```

| id | type | location |
|---|---|---|
| span 1 | bytes[100] | Memory |
| span 2  | Map<address, bytes[100]> | Storage |
| span 3  | address | Value |

The crucial difference with this approach is that our compiler pass is not responsible for juggling things like scope or figuring out expression types. Instead, it just looks up information about AST elements by their span.

The semantic analysis pass would look pretty similar to the existing compiler pass, in that we would still be using the same AST traversal functions and data structures (like scope). The only difference is that it would not be creating a Yul AST, but would instead be building up context information and validating semantics.

**Implementation of this refactor would involve a few things:**
- [ ] create a new lib called *semantics*
- [ ] copy the [namespace](https://github.com/ethereum/fe/tree/master/compiler/src/yul/namespace) module into the semantics lib
- [ ] copy the [existing AST traversal functions](https://github.com/ethereum/fe/tree/master/compiler/src/yul/mappers) in the compiler lib to the semantics lib and refactor them to build a `Context` instance, instead of generating Yul
- [ ] remove all uses of the namespace mod in the compiler pass and replace with the use of `Context`

The first 3 steps can be done without touching the compiler lib and the final step shouldn't be terribly complicated.
