### ISSUE TITLE
Website Meta Issue

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/fe#393]
### Quick & Dirty list of all things web

- [ ] We currently have fe.ethereum.org Should we get a more dedicated website such as http://fe-lang.org ?
- [ ] Discuss moving everything compiler related into a subdirectory
- [ ] Should we design a "Oh, snap, we are actively working on this page" that we can temporary link to for things like the playground that aren't yet ready but so we can keep them on the frontpage already?
- [ ] ...

**Comment by satyamakgec** [comment]
Yeah, I think we should go for a more dedicated website URL `https://fe-lang.org` and different URLs like felang.com or fe.ethereum.org can re-route to fe-lang.org something very similar to rust-lang.org. 

We can have mock pages that will have a gif like "Under Construction".  eg - https://media.giphy.com/media/ocuQpTqeFlDOP4fFJI/giphy.gif
