### ISSUE TITLE
Project goals/roadmap (README improvements)

### ISSUE THREAD

**Issue by davesque** [ethereum/fe#5]
The README was just updated to include more information about the overall goals of the Rust Vyper project and its relationship with the existing Vyper project.  Things that still need doing:

* [ ] Editing/wording improvements
* [ ] Inclusion of any additional goals or information that may have been left out
* [x] Inclusion of a project roadmap with an emphasis on near-term milestones

**Comment by sbillig** [comment]
Closing as defunct
