### ISSUE TITLE
[FOLLOW UP] constant evaluation

### ISSUE THREAD

**Issue by Y-Nak** [ethereum/fe#652]
This is a follow-up issue for #649 

# TODO
* [ ] Write Doc for constant evaluation when #646 is merged
* [ ] Allow `path` use in constant expresssion
* [ ] Allow non base type to be const
* [ ] const fn support
